# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-
      - run: yarn test

  build_docs:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-
      - run: yarn docz build

  build_development:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-
      - run: NODE_ENV=development yarn webpack


  build_production:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-
      - run: NODE_ENV=production yarn webpack -p

  check_in_build:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-
      - run: git add ./build ./docs
      - run: git commit -m 'CircleCI - update build & docs'
      - run: git push origin HEAD

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build_development:
          requires:
            - setup
      - build_production:
          requires:
            - setup
      - build_docs:
          requires:
            - setup
      - check_in_build:
          requires:
            - test
            - build_development
            - build_production
            - build_docs
